# set variables in build_scripts/build_variables.sh

package:
  name: casm-boost
  version: {{ CASM_BOOST_VERSION }}

source:
  url: {{ CASM_BOOST_URL }}
  sha256: {{ CASM_BOOST_SHA256 }}

build:
  number: {{ CASM_BOOST_BUILD_NUMBER }}
  string: {{ CASM_BOOST_CONDAGCC_BUILD_STR }}
  script_env:
    - CASM_NCPU
  track_features:
    - condagcc

requirements:
  build:
    - wget
    - bzip2
    - gcc_linux-64 {{ CASM_CONDAGCC_VERSION }}*
    - gxx_linux-64 {{ CASM_CONDAGCC_VERSION }}*
    - gfortran_linux-64 {{ CASM_CONDAGCC_VERSION }}*

  run:


about:
  home: http://www.boost.org/
  license: Boost
  license_file: LICENSE_1_0.txt
  summary: Boost {{ CASM_BOOST_VERSION }} minimal build for CASM
