# http://www.scons.org/doc/production/HTML/scons-user.html
# This is: h/casm/BP_C++/SConscript

import os, glob

Import('env')

bpcpp_lib_src = glob.glob('*.cc')

#currently not using gzstream in casm, so not compiling it

bpcpp_lib_sobj = env.SharedObject(bpcpp_lib_src)
env['COMPILE_TARGETS'] = env['COMPILE_TARGETS'] + bpcpp_lib_sobj
env['CASM_SOBJ'] = env['CASM_SOBJ'] + bpcpp_lib_sobj
