# set variables in build_scripts/build_variables.sh

package:
  name: casm-cpp
  version: {{ CASM_CONDA_VERSION }}

source:
  git_url: {{ CASM_REPO }}
  git_rev: {{ CASM_BRANCH }}

build:
  number: {{ CASM_BUILD_NUMBER }}
  string: {{ CASM_CONDAGCC_CENTOS6_BUILD_STR }}
  script_env:
    - CASM_NCPU
  features:
    - condagcc_centos6

requirements:
  build:
    - python {{ CASM_PYTHON_VERSION }}*
    - casm-boost {{ CASM_BOOST_VERSION }} {{ CASM_BOOST_CONDAGCC_CENTOS6_BUILD_STR }}
    - m4 >=1.4.18
    - autoconf
    - automake
    - make
    - libtool
    - pkg-config
    - wget
    - bzip2
    - six
    - gcc_linux-64 {{ CASM_CONDAGCC_CENTOS6_VERSION }}*
    - gxx_linux-64 {{ CASM_CONDAGCC_CENTOS6_VERSION }}*
    - gfortran_linux-64 {{ CASM_CONDAGCC_CENTOS6_VERSION }}*

  run:
    - casm-boost {{ CASM_BOOST_VERSION }} {{ CASM_BOOST_CONDAGCC_CENTOS6_BUILD_STR }}
    - gcc_linux-64 {{ CASM_CONDAGCC_CENTOS6_VERSION }}*
    - gxx_linux-64 {{ CASM_CONDAGCC_CENTOS6_VERSION }}*
    - gfortran_linux-64 {{ CASM_CONDAGCC_CENTOS6_VERSION }}*

about:
  home: {{ CASM_URL }}
  license: LGPLv2
  license_file: LICENSE
  summary: CASM library and c++ based command line tools
