# http://www.scons.org/doc/production/HTML/scons-user.html
# This is: tests/casm/SConscript

import os, glob
from os.path import join

# Import dependencies
Import('env', 'casm', 'casm_lib')
dependencies = [casm, casm_lib]

# Specify the targets: files and directories written by the test
bset_dir = join('basis_sets', 'bset.default')
bset_files = glob.glob( join(bset_dir, '*CLUST*') )
clexulator_files = glob.glob( join(bset_dir, '*Clexulator.*') )

targets = [
  '.casm', 'LOG', 'prim.json', 
  'training_data', 'symmetry', 'cluster_expansions', 'query_results.txt'
] + bset_files + clexulator_files + [ join(bset_dir, x) for x in ['eci.in', 'prim_nlist.json', 'corr.in', 'clust.json']]

# Specify the command to run the test the Alias
casm_test = env.Command(targets, dependencies, 'cd ' + os.getcwd() + ' && bash ' + os.path.join(os.getcwd(), 'test.sh'))
env.Alias('casm_test', casm_test)

if 'casm_test' in COMMAND_LINE_TARGETS:
  env['IS_TEST'] = 1

# Specify how to clean up
Clean(casm_test,  targets)

# Specify that the command should always be run when requested
AlwaysBuild(casm_test)

