# http://www.scons.org/doc/production/HTML/scons-user.html
# This is: src/casm/SConscript

import os, glob
from glob import glob
from os.path import join

Import('env')

#####
# CASM non Monte Carlo code

# build version
SConscript(['version/SConscript'], {'env':env})

# get source files
casm_lib_src_dir = [
  'casm_io', 'container', 'crystallography', 'symmetry', 'basis_set', 'clusterography', 'kspace', 
  'misc', 'strain', 'clex', 'hull', 'phonon', 'monte_carlo', 'monte_carlo/grand_canonical'
]
casm_lib_src = ['CASM_global_definitions.cc'] + [glob(join(x,'*.cc')) for x in casm_lib_src_dir]

casm_lib_sobj = env.SharedObject(casm_lib_src)
env['COMPILE_TARGETS'] = env['COMPILE_TARGETS'] + casm_lib_sobj
env['CASM_SOBJ'] = env['CASM_SOBJ'] + casm_lib_sobj
