# set variables in build_scripts/build_variables.sh

package:
  name: casm
  version: {{ CASM_CONDA_VERSION }}

build:
  number: {{ CASM_BUILD_NUMBER }}
  string: {{ CASM_CONDAGCC_CENTOS6_BUILD_STR }}
  features:
    - condagcc_centos6

requirements:
  build:
    - python {{ CASM_PYTHON_VERSION }}*

  run:
    - python {{ CASM_PYTHON_VERSION }}*
    - casm-boost {{ CASM_BOOST_VERSION }} {{ CASM_BOOST_CONDAGCC_CENTOS6_BUILD_STR }}
    - casm-cpp {{ CASM_CONDA_VERSION }} {{ CASM_CONDAGCC_CENTOS6_BUILD_STR }}
    - casm-python {{ CASM_CONDA_VERSION }} {{ CASM_BUILD_NUMBER }}

about:
  home: {{ CASM_URL }}
  license: LGPLv2
  summary: CASM metapackage to install all components
