# http://www.scons.org/doc/production/HTML/scons-user.html
# This is: apps/eci_search

import os

Import('env')

# Build instructions
eci_search_include = env['CPPPATH'] + ['.', '../../include/casm/BP_C++', '../../include/casm/casm_io', '../../src/casm/BP_C++', '../../src/casm/casm_io']
libs = ['boost_system', 'boost_filesystem', 'pthread']

eci_search_obj = env.Object('eci_search.cpp', CPPPATH = eci_search_include)

eci_search = env.Program(os.path.join(env['CASM_BIN'], "eci_search"),
                   eci_search_obj,
                   LIBS=libs)
env.Alias('eci_search', eci_search)
Default(eci_search)
Export('eci_search')
env['COMPILE_TARGETS'] = env['COMPILE_TARGETS'] + [eci_search, eci_search_obj]


# Install instructions
eci_search_install = env.Install(os.path.join(env['PREFIX'],'bin'), eci_search)
env.Alias('eci_search_install', eci_search_install)
Export('eci_search_install')
env['INSTALL_TARGETS'] = env['INSTALL_TARGETS'] + [eci_search_install]
  
if 'eci_search_install' in COMMAND_LINE_TARGETS:
    env['IS_INSTALL'] = 1
