# http://www.scons.org/doc/production/HTML/scons-user.html
# This is: tests/eci_search/SConscript

import os, glob
from os.path import join

# Import dependencies
Import('env', 'eci_search')

# Specify the targets: files and directories written by the test
targets = ['below.hull', 'corr.covar', 'eci.out', 'population', 'energy.clex'] + glob.glob('clex_results*') + glob.glob('hull*')

# Specify the command to run the test the Alias
eci_search_test = env.Command(targets, eci_search, 'cd ' + os.getcwd() + ' && bash ' + os.path.join(os.getcwd(), 'test.sh'))
env.Alias('eci_search_test', eci_search_test)

if 'eci_search_test' in COMMAND_LINE_TARGETS:
  env['IS_TEST'] = 1

# Specify how to clean up
Clean(eci_search_test,  targets)

# Specify that the command should always be run when requested
AlwaysBuild(eci_search_test)

