name: Testing on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set up requirements
        run: |
          sudo apt-get install build-essential autoconf libboost-all-dev ccache
          pip install --upgrade pip wheel
          pip install GitPython
      
      - name: Cache casm build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-build

      - name: Create casm build
        shell: bash
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: mkdir build

      - name: Build casm
        shell: bash
        run: |
          git submodule update --init --recursive
          bash bootstrap.sh
          cd build
          ../configure CC='ccache gcc' CXX='ccache g++' CXXFLAGS='-O3'
          make -j4

      - name: Test casm
        shell: bash
        run: |
          cd build
          pwd
          #make check -j4
