name: Testing on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up g++/gcc/make/autconf/boost
        run: |
          sudo apt install build-essential
          sudo apt install autoconf
          sudo apt install libboost-all-dev

      - name: Install GitPython
        run: |
          pip install --upgrade pip wheel
          pip install GitPython 
      
      - name: Build casm
        shell: bash

        run: |
          ls -l include/casm/external/
          ls -l submdoules/eigen/Eigen/
          #bash bootstrap.sh
          #mkdir build && cd build
          #../configure CC='gcc' CXX='g++' CXXFLAGS='-O3'
          #make -j4
        


